// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc6ZFrdG_ZIwJj4mAJg2uD02T9SzPxb-Q',
    appId: '1:554255921032:web:acf0cd8165fb1f30a8143d',
    messagingSenderId: '554255921032',
    projectId: 'damripool-b3a06',
    authDomain: 'damripool-b3a06.firebaseapp.com',
    storageBucket: 'damripool-b3a06.appspot.com',
    measurementId: 'G-DRC91LXEMZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF4161snEBkWKhVtkCbGnPr5vRfA9xsaU',
    appId: '1:554255921032:android:f425432738f7f1b5a8143d',
    messagingSenderId: '554255921032',
    projectId: 'damripool-b3a06',
    storageBucket: 'damripool-b3a06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCihJwrYHJ2szGVQlyDki5jQbWCw1JWgr8',
    appId: '1:554255921032:ios:c23a442b0bf8de5aa8143d',
    messagingSenderId: '554255921032',
    projectId: 'damripool-b3a06',
    storageBucket: 'damripool-b3a06.appspot.com',
    iosClientId: '554255921032-03s1rt0mlqggh3718f31qhm432n5d66d.apps.googleusercontent.com',
    iosBundleId: 'com.example.damri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCihJwrYHJ2szGVQlyDki5jQbWCw1JWgr8',
    appId: '1:554255921032:ios:c23a442b0bf8de5aa8143d',
    messagingSenderId: '554255921032',
    projectId: 'damripool-b3a06',
    storageBucket: 'damripool-b3a06.appspot.com',
    iosClientId: '554255921032-03s1rt0mlqggh3718f31qhm432n5d66d.apps.googleusercontent.com',
    iosBundleId: 'com.example.damri',
  );
}
